#include "CompaireTest.hpp"

TEST_F(CTypeCompaireTest, int8_string_basic) {
    CTYPE_ASSERT_EQ("123", CPE_DR_TYPE_INT8, CPE_DR_TYPE_STRING);
    CTYPE_ASSERT_LT("123", CPE_DR_TYPE_INT8, "3456", CPE_DR_TYPE_STRING);
    CTYPE_ASSERT_LT("-123", CPE_DR_TYPE_INT8, "3456", CPE_DR_TYPE_STRING);
    CTYPE_ASSERT_LT("-123", CPE_DR_TYPE_INT8, "-122", CPE_DR_TYPE_STRING);
}

TEST_F(CTypeCompaireTest, uint8_string_basic) {
    CTYPE_ASSERT_EQ("123", CPE_DR_TYPE_UINT8, CPE_DR_TYPE_STRING);
    CTYPE_ASSERT_LT("123", CPE_DR_TYPE_UINT8, "3456", CPE_DR_TYPE_STRING);
    CTYPE_ASSERT_LT("123", CPE_DR_TYPE_UINT8, "3456", CPE_DR_TYPE_STRING);
    CTYPE_ASSERT_LT("-123", CPE_DR_TYPE_STRING, "122", CPE_DR_TYPE_UINT8);
}
