#include "payment_svr_adapter_type.h"

PAYMENT_DECLARE_ADAPTER(iapppay);
PAYMENT_DECLARE_ADAPTER(iap);
PAYMENT_DECLARE_ADAPTER(qihoo);
PAYMENT_DECLARE_ADAPTER(damai);
PAYMENT_DECLARE_ADAPTER(unicompay_offline);
//PAYMENT_DECLARE_ADAPTER(unicompay_online);
PAYMENT_DECLARE_ADAPTER(cmccpay_offline);
//PAYMENT_DECLARE_ADAPTER(cmccpay_online);
PAYMENT_DECLARE_ADAPTER(telecompay_offline);
//PAYMENT_DECLARE_ADAPTER(telecompay_online);
PAYMENT_DECLARE_ADAPTER(haoxin_offline);
//PAYMENT_DECLARE_ADAPTER(haoxin_online);
PAYMENT_DECLARE_ADAPTER(chuangku_offline);
//PAYMENT_DECLARE_ADAPTER(chuangku_online);
struct payment_svr_adapter_type g_adapter_types[] = {
    PAYMENT_IMPL_ADAPTER(iapppay, PAYMENT_RECHARGE_SERVICE_IAPPPAY),
    PAYMENT_IMPL_ADAPTER(iap, PAYMENT_RECHARGE_SERVICE_IAP),
    PAYMENT_IMPL_ADAPTER(qihoo, PAYMENT_RECHARGE_SERVICE_QIHOO),
    PAYMENT_IMPL_ADAPTER(damai, PAYMENT_RECHARGE_SERVICE_DAMAI),
    PAYMENT_IMPL_ADAPTER(unicompay_offline, PAYMENT_RECHARGE_SERVICE_UNICOMPAY_OFFLINE),
    //PAYMENT_IMPL_ADAPTER(unicompay_online, PAYMENT_RECHARGE_SERVICE_UNICOMPAY_ONLINE),
    PAYMENT_IMPL_ADAPTER(cmccpay_offline, PAYMENT_RECHARGE_SERVICE_CMCCPAY_OFFLINE),
    //PAYMENT_IMPL_ADAPTER(unicompay_online, PAYMENT_RECHARGE_SERVICE_CMCCPAY_ONLINE),
    PAYMENT_IMPL_ADAPTER(telecompay_offline, PAYMENT_RECHARGE_SERVICE_TELECOMPAY_OFFLINE),
    //PAYMENT_IMPL_ADAPTER(telecompay_online, PAYMENT_RECHARGE_SERVICE_TELECOMPAY_ONLINE),
    PAYMENT_IMPL_ADAPTER(haoxin_offline, PAYMENT_RECHARGE_SERVICE_HAOXIN_OFFLINE),
    //PAYMENT_IMPL_ADAPTER(haoxin_online, PAYMENT_RECHARGE_SERVICE_HAOXIN_ONLINE),
    PAYMENT_IMPL_ADAPTER(chuangku_offline, PAYMENT_RECHARGE_SERVICE_CHUANGKU_OFFLINE),
    //PAYMENT_IMPL_ADAPTER(chuangku_online, PAYMENT_RECHARGE_SERVICE_CHUANGKU_ONLINE),
};

uint8_t g_adapter_type_count = CPE_ARRAY_SIZE(g_adapter_types);
