#include "cpe/utils/stream_mem.h"
#include "cpe/utils/base64.h"
#include "cpe/utils/tests-env/test-fixture.hpp"

class Base64Test : public testenv::fixture<> {
public:
    const char * encode(const char * input) {
        int input_len = strlen(input);
        read_stream_mem is = CPE_READ_STREAM_MEM_INITIALIZER(input, input_len);

        int output_len = input_len / 3 * 4 + 100;
        void * output_buf = t_tmp_alloc(output_len);
        write_stream_mem os = CPE_WRITE_STREAM_MEM_INITIALIZER(output_buf, output_len);

        cpe_base64_encode((write_stream_t)&os, (read_stream_t)&is);
        stream_putc((write_stream_t)&os, 0);

        return (const char *)output_buf;
    }

    const char * decode(const char * input) {
        int input_len = strlen(input);
        read_stream_mem is = CPE_READ_STREAM_MEM_INITIALIZER(input, input_len);

        int output_len = input_len + 100;
        void * output_buf = t_tmp_alloc(output_len);
        write_stream_mem os = CPE_WRITE_STREAM_MEM_INITIALIZER(output_buf, output_len);

        cpe_base64_decode((write_stream_t)&os, (read_stream_t)&is);
        stream_putc((write_stream_t)&os, 0);

        return (const char *)output_buf;
    }
};

TEST_F(Base64Test, encode) {
    EXPECT_STREQ(
        "MTIzNDU2"
        ,
        encode("123456"));
}

TEST_F(Base64Test, decode) {
    EXPECT_STREQ(
        "123456"
        ,
        decode("MTIzNDU2"));
}

TEST_F(Base64Test, encode_example_iap) {
    EXPECT_STREQ(
        "ewoJInNpZ25hdHVyZSIgPSAiQWw2enZGWkpMeVJtMjZtVlNNZGNqOVpqT0xhVFNmYVUwbXZoU2dJVEYxQUt5UzN0QXpFazhhYlky"
        "SHU3Z2NWN3FuZHpaM2JTQjQrQXcvZ1JrV2xxYWtpSVBIRy9jNjRSNEkwK3poT1pBbUhpQnFiR2FDOW1aNHNDVGJIS01xaWtUcjh5"
        "ak1qMWpKMXV0QWZpZWJvMmtnZlgzVFVlVmg5OVBXeE9YUWhpV0cwVUFBQURWekNDQTFNd2dnSTdvQU1DQVFJQ0NHVVVrVTNaV0FT"
        "MU1BMEdDU3FHU0liM0RRRUJCUVVBTUg4eEN6QUpCZ05WQkFZVEFsVlRNUk13RVFZRFZRUUtEQXBCY0hCc1pTQkpibU11TVNZd0pB"
        "WURWUVFMREIxQmNIQnNaU0JEWlhKMGFXWnBZMkYwYVc5dUlFRjFkR2h2Y21sMGVURXpNREVHQTFVRUF3d3FRWEJ3YkdVZ2FWUjFi"
        "bVZ6SUZOMGIzSmxJRU5sY25ScFptbGpZWFJwYjI0Z1FYVjBhRzl5YVhSNU1CNFhEVEE1TURZeE5USXlNRFUxTmxvWERURTBNRFl4"
        "TkRJeU1EVTFObG93WkRFak1DRUdBMVVFQXd3YVVIVnlZMmhoYzJWU1pXTmxhWEIwUTJWeWRHbG1hV05oZEdVeEd6QVpCZ05WQkFz"
        "TUVrRndjR3hsSUdsVWRXNWxjeUJUZEc5eVpURVRNQkVHQTFVRUNnd0tRWEJ3YkdVZ1NXNWpMakVMTUFrR0ExVUVCaE1DVlZNd2da"
        "OHdEUVlKS29aSWh2Y05BUUVCQlFBRGdZMEFNSUdKQW9HQkFNclJqRjJjdDRJclNkaVRDaGFJMGc4cHd2L2NtSHM4cC9Sd1YvcnQv"
        "OTFYS1ZoTmw0WElCaW1LalFRTmZnSHNEczZ5anUrK0RyS0pFN3VLc3BoTWRkS1lmRkU1ckdYc0FkQkVqQndSSXhleFRldngzSExF"
        "RkdBdDFtb0t4NTA5ZGh4dGlJZERnSnYyWWFWczQ5QjB1SnZOZHk2U01xTk5MSHNETHpEUzlvWkhBZ01CQUFHamNqQndNQXdHQTFV"
        "ZEV3RUIvd1FDTUFBd0h3WURWUjBqQkJnd0ZvQVVOaDNvNHAyQzBnRVl0VEpyRHRkREM1RllRem93RGdZRFZSMFBBUUgvQkFRREFn"
        "ZUFNQjBHQTFVZERnUVdCQlNwZzRQeUdVakZQaEpYQ0JUTXphTittVjhrOVRBUUJnb3Foa2lHOTJOa0JnVUJCQUlGQURBTkJna3Fo"
        "a2lHOXcwQkFRVUZBQU9DQVFFQUVhU2JQanRtTjRDL0lCM1FFcEszMlJ4YWNDRFhkVlhBZVZSZVM1RmFaeGMrdDg4cFFQOTNCaUF4"
        "dmRXLzNlVFNNR1k1RmJlQVlMM2V0cVA1Z204d3JGb2pYMGlreVZSU3RRKy9BUTBLRWp0cUIwN2tMczlRVWU4Y3pSOFVHZmRNMUV1"
        "bVYvVWd2RGQ0TndOWXhMUU1nNFdUUWZna1FRVnk4R1had1ZIZ2JFL1VDNlk3MDUzcEdYQms1MU5QTTN3b3hoZDNnU1JMdlhqK2xv"
        "SHNTdGNURXFlOXBCRHBtRzUrc2s0dHcrR0szR01lRU41LytlMVFUOW5wL0tsMW5qK2FCdzdDMHhzeTBiRm5hQWQxY1NTNnhkb3J5"
        "L0NVdk02Z3RLc21uT09kcVRlc2JwMGJzOHNuNldxczBDOWRnY3hSSHVPTVoydG04bnBMVW03YXJnT1N6UT09IjsKCSJwdXJjaGFz"
        "ZS1pbmZvIiA9ICJld29KSW05eWFXZHBibUZzTFhCMWNtTm9ZWE5sTFdSaGRHVXRjSE4wSWlBOUlDSXlNREUwTFRBeExURTFJREl3"
        "T2pJMk9qQTJJRUZ0WlhKcFkyRXZURzl6WDBGdVoyVnNaWE1pT3dvSkluVnVhWEYxWlMxcFpHVnVkR2xtYVdWeUlpQTlJQ0kyTkdG"
        "aE1EVTJNMkV4WkRZM056WmxabUprT1RVd1lUSTNaR1F3T0RJMU5EUXlZalZtWlRObElqc0tDU0p2Y21sbmFXNWhiQzEwY21GdWMy"
        "RmpkR2x2YmkxcFpDSWdQU0FpTVRBd01EQXdNREE1T0RZeU1URTNNU0k3Q2draVluWnljeUlnUFNBaU1pNHlJanNLQ1NKMGNtRnVj"
        "MkZqZEdsdmJpMXBaQ0lnUFNBaU1UQXdNREF3TURBNU9EWXlNVEUzTVNJN0Nna2ljWFZoYm5ScGRIa2lJRDBnSWpFaU93b0pJbTl5"
        "YVdkcGJtRnNMWEIxY21Ob1lYTmxMV1JoZEdVdGJYTWlJRDBnSWpFek9EazRORFl6TmpZeE9EVWlPd29KSW5WdWFYRjFaUzEyWlc1"
        "a2IzSXRhV1JsYm5ScFptbGxjaUlnUFNBaVJqVkdOME5GUlRBdE1qVTVNQzAwTlVJeExVRTBSalF0UlRFek0wSTNNVFpGTXpNMElq"
        "c0tDU0p3Y205a2RXTjBMV2xrSWlBOUlDSmpiMjB1ZERRdWRHaGxPVzl3TG1ScFlXMXZibVF1TmpZd0lqc0tDU0pwZEdWdExXbGtJ"
        "aUE5SUNJM016QXpNVEUwTmpZaU93b0pJbUpwWkNJZ1BTQWlZMjl0TG5RMExuUm9aVGx2Y0NJN0Nna2ljSFZ5WTJoaGMyVXRaR0Yw"
        "WlMxdGN5SWdQU0FpTVRNNE9UZzBOak0yTmpFNE5TSTdDZ2tpY0hWeVkyaGhjMlV0WkdGMFpTSWdQU0FpTWpBeE5DMHdNUzB4TmlB"
        "d05Eb3lOam93TmlCRmRHTXZSMDFVSWpzS0NTSndkWEpqYUdGelpTMWtZWFJsTFhCemRDSWdQU0FpTWpBeE5DMHdNUzB4TlNBeU1E"
        "b3lOam93TmlCQmJXVnlhV05oTDB4dmMxOUJibWRsYkdWeklqc0tDU0p2Y21sbmFXNWhiQzF3ZFhKamFHRnpaUzFrWVhSbElpQTlJ"
        "Q0l5TURFMExUQXhMVEUySURBME9qSTJPakEySUVWMFl5OUhUVlFpT3dwOSI7CgkiZW52aXJvbm1lbnQiID0gIlNhbmRib3giOwoJ"
        "InBvZCIgPSAiMTAwIjsKCSJzaWduaW5nLXN0YXR1cyIgPSAiMCI7Cn0="
        ,
        encode(
            "{\n"
            "	\"signature\" = \"Al6zvFZJLyRm26mVSMdcj9ZjOLaTSfaU0mvhSgITF1AKyS3tAzEk8abY2Hu7gcV7qndzZ3bSB4+Aw/gRk"
            "WlqakiIPHG/c64R4I0+zhOZAmHiBqbGaC9mZ4sCTbHKMqikTr8yjMj1jJ1utAfiebo2kgfX3TUeVh99PWxOXQhiWG0UAAADVzCCA"
            "1MwggI7oAMCAQICCGUUkU3ZWAS1MA0GCSqGSIb3DQEBBQUAMH8xCzAJBgNVBAYTAlVTMRMwEQYDVQQKDApBcHBsZSBJbmMuMSYwJ"
            "AYDVQQLDB1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEzMDEGA1UEAwwqQXBwbGUgaVR1bmVzIFN0b3JlIENlcnRpZmljY"
            "XRpb24gQXV0aG9yaXR5MB4XDTA5MDYxNTIyMDU1NloXDTE0MDYxNDIyMDU1NlowZDEjMCEGA1UEAwwaUHVyY2hhc2VSZWNlaXB0Q"
            "2VydGlmaWNhdGUxGzAZBgNVBAsMEkFwcGxlIGlUdW5lcyBTdG9yZTETMBEGA1UECgwKQXBwbGUgSW5jLjELMAkGA1UEBhMCVVMwg"
            "Z8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAMrRjF2ct4IrSdiTChaI0g8pwv/cmHs8p/RwV/rt/91XKVhNl4XIBimKjQQNfgHsD"
            "s6yju++DrKJE7uKsphMddKYfFE5rGXsAdBEjBwRIxexTevx3HLEFGAt1moKx509dhxtiIdDgJv2YaVs49B0uJvNdy6SMqNNLHsDL"
            "zDS9oZHAgMBAAGjcjBwMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUNh3o4p2C0gEYtTJrDtdDC5FYQzowDgYDVR0PAQH/BAQDA"
            "geAMB0GA1UdDgQWBBSpg4PyGUjFPhJXCBTMzaN+mV8k9TAQBgoqhkiG92NkBgUBBAIFADANBgkqhkiG9w0BAQUFAAOCAQEAEaSbP"
            "jtmN4C/IB3QEpK32RxacCDXdVXAeVReS5FaZxc+t88pQP93BiAxvdW/3eTSMGY5FbeAYL3etqP5gm8wrFojX0ikyVRStQ+/AQ0KE"
            "jtqB07kLs9QUe8czR8UGfdM1EumV/UgvDd4NwNYxLQMg4WTQfgkQQVy8GXZwVHgbE/UC6Y7053pGXBk51NPM3woxhd3gSRLvXj+l"
            "oHsStcTEqe9pBDpmG5+sk4tw+GK3GMeEN5/+e1QT9np/Kl1nj+aBw7C0xsy0bFnaAd1cSS6xdory/CUvM6gtKsmnOOdqTesbp0bs"
            "8sn6Wqs0C9dgcxRHuOMZ2tm8npLUm7argOSzQ==\";\n"
            "	\"purchase-info\" = \"ewoJIm9yaWdpbmFsLX"
            "B1cmNoYXNlLWRhdGUtcHN0IiA9ICIyMDE0LTAxLTE1IDIwOjI2OjA2IEFtZXJpY2EvTG9zX0FuZ2VsZXMiOwoJInVuaXF1ZS1pZG"
            "VudGlmaWVyIiA9ICI2NGFhMDU2M2ExZDY3NzZlZmJkOTUwYTI3ZGQwODI1NDQyYjVmZTNlIjsKCSJvcmlnaW5hbC10cmFuc2FjdG"
            "lvbi1pZCIgPSAiMTAwMDAwMDA5ODYyMTE3MSI7CgkiYnZycyIgPSAiMi4yIjsKCSJ0cmFuc2FjdGlvbi1pZCIgPSAiMTAwMDAwMD"
            "A5ODYyMTE3MSI7CgkicXVhbnRpdHkiID0gIjEiOwoJIm9yaWdpbmFsLXB1cmNoYXNlLWRhdGUtbXMiID0gIjEzODk4NDYzNjYxOD"
            "UiOwoJInVuaXF1ZS12ZW5kb3ItaWRlbnRpZmllciIgPSAiRjVGN0NFRTAtMjU5MC00NUIxLUE0RjQtRTEzM0I3MTZFMzM0IjsKCS"
            "Jwcm9kdWN0LWlkIiA9ICJjb20udDQudGhlOW9wLmRpYW1vbmQuNjYwIjsKCSJpdGVtLWlkIiA9ICI3MzAzMTE0NjYiOwoJImJpZC"
            "IgPSAiY29tLnQ0LnRoZTlvcCI7CgkicHVyY2hhc2UtZGF0ZS1tcyIgPSAiMTM4OTg0NjM2NjE4NSI7CgkicHVyY2hhc2UtZGF0ZS"
            "IgPSAiMjAxNC0wMS0xNiAwNDoyNjowNiBFdGMvR01UIjsKCSJwdXJjaGFzZS1kYXRlLXBzdCIgPSAiMjAxNC0wMS0xNSAyMDoyNj"
            "owNiBBbWVyaWNhL0xvc19BbmdlbGVzIjsKCSJvcmlnaW5hbC1wdXJjaGFzZS1kYXRlIiA9ICIyMDE0LTAxLTE2IDA0OjI2OjA2IE"
            "V0Yy9HTVQiOwp9\";\n"
            "	\"environment\" = \"Sandbox\";\n"
            "	\"pod\" = \"100\";\n"
            "	\"signing-status\" = \"0\";\n"
            "}"
            ));
}


TEST_F(Base64Test, decode_example_iap) {
    EXPECT_STREQ(
        "{\n"
        "	\"signature\" = \"Al6zvFZJLyRm26mVSMdcj9ZjOLaTSfaU0mvhSgITF1AKyS3tAzEk8abY2Hu7gcV7qndzZ3bSB4+Aw/gRk"
        "WlqakiIPHG/c64R4I0+zhOZAmHiBqbGaC9mZ4sCTbHKMqikTr8yjMj1jJ1utAfiebo2kgfX3TUeVh99PWxOXQhiWG0UAAADVzCCA"
        "1MwggI7oAMCAQICCGUUkU3ZWAS1MA0GCSqGSIb3DQEBBQUAMH8xCzAJBgNVBAYTAlVTMRMwEQYDVQQKDApBcHBsZSBJbmMuMSYwJ"
        "AYDVQQLDB1BcHBsZSBDZXJ0aWZpY2F0aW9uIEF1dGhvcml0eTEzMDEGA1UEAwwqQXBwbGUgaVR1bmVzIFN0b3JlIENlcnRpZmljY"
        "XRpb24gQXV0aG9yaXR5MB4XDTA5MDYxNTIyMDU1NloXDTE0MDYxNDIyMDU1NlowZDEjMCEGA1UEAwwaUHVyY2hhc2VSZWNlaXB0Q"
        "2VydGlmaWNhdGUxGzAZBgNVBAsMEkFwcGxlIGlUdW5lcyBTdG9yZTETMBEGA1UECgwKQXBwbGUgSW5jLjELMAkGA1UEBhMCVVMwg"
        "Z8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAMrRjF2ct4IrSdiTChaI0g8pwv/cmHs8p/RwV/rt/91XKVhNl4XIBimKjQQNfgHsD"
        "s6yju++DrKJE7uKsphMddKYfFE5rGXsAdBEjBwRIxexTevx3HLEFGAt1moKx509dhxtiIdDgJv2YaVs49B0uJvNdy6SMqNNLHsDL"
        "zDS9oZHAgMBAAGjcjBwMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUNh3o4p2C0gEYtTJrDtdDC5FYQzowDgYDVR0PAQH/BAQDA"
        "geAMB0GA1UdDgQWBBSpg4PyGUjFPhJXCBTMzaN+mV8k9TAQBgoqhkiG92NkBgUBBAIFADANBgkqhkiG9w0BAQUFAAOCAQEAEaSbP"
        "jtmN4C/IB3QEpK32RxacCDXdVXAeVReS5FaZxc+t88pQP93BiAxvdW/3eTSMGY5FbeAYL3etqP5gm8wrFojX0ikyVRStQ+/AQ0KE"
        "jtqB07kLs9QUe8czR8UGfdM1EumV/UgvDd4NwNYxLQMg4WTQfgkQQVy8GXZwVHgbE/UC6Y7053pGXBk51NPM3woxhd3gSRLvXj+l"
        "oHsStcTEqe9pBDpmG5+sk4tw+GK3GMeEN5/+e1QT9np/Kl1nj+aBw7C0xsy0bFnaAd1cSS6xdory/CUvM6gtKsmnOOdqTesbp0bs"
        "8sn6Wqs0C9dgcxRHuOMZ2tm8npLUm7argOSzQ==\";\n"
        "	\"purchase-info\" = \"ewoJIm9yaWdpbmFsLX"
        "B1cmNoYXNlLWRhdGUtcHN0IiA9ICIyMDE0LTAxLTE1IDIwOjI2OjA2IEFtZXJpY2EvTG9zX0FuZ2VsZXMiOwoJInVuaXF1ZS1pZG"
        "VudGlmaWVyIiA9ICI2NGFhMDU2M2ExZDY3NzZlZmJkOTUwYTI3ZGQwODI1NDQyYjVmZTNlIjsKCSJvcmlnaW5hbC10cmFuc2FjdG"
        "lvbi1pZCIgPSAiMTAwMDAwMDA5ODYyMTE3MSI7CgkiYnZycyIgPSAiMi4yIjsKCSJ0cmFuc2FjdGlvbi1pZCIgPSAiMTAwMDAwMD"
        "A5ODYyMTE3MSI7CgkicXVhbnRpdHkiID0gIjEiOwoJIm9yaWdpbmFsLXB1cmNoYXNlLWRhdGUtbXMiID0gIjEzODk4NDYzNjYxOD"
        "UiOwoJInVuaXF1ZS12ZW5kb3ItaWRlbnRpZmllciIgPSAiRjVGN0NFRTAtMjU5MC00NUIxLUE0RjQtRTEzM0I3MTZFMzM0IjsKCS"
        "Jwcm9kdWN0LWlkIiA9ICJjb20udDQudGhlOW9wLmRpYW1vbmQuNjYwIjsKCSJpdGVtLWlkIiA9ICI3MzAzMTE0NjYiOwoJImJpZC"
        "IgPSAiY29tLnQ0LnRoZTlvcCI7CgkicHVyY2hhc2UtZGF0ZS1tcyIgPSAiMTM4OTg0NjM2NjE4NSI7CgkicHVyY2hhc2UtZGF0ZS"
        "IgPSAiMjAxNC0wMS0xNiAwNDoyNjowNiBFdGMvR01UIjsKCSJwdXJjaGFzZS1kYXRlLXBzdCIgPSAiMjAxNC0wMS0xNSAyMDoyNj"
        "owNiBBbWVyaWNhL0xvc19BbmdlbGVzIjsKCSJvcmlnaW5hbC1wdXJjaGFzZS1kYXRlIiA9ICIyMDE0LTAxLTE2IDA0OjI2OjA2IE"
        "V0Yy9HTVQiOwp9\";\n"
        "	\"environment\" = \"Sandbox\";\n"
        "	\"pod\" = \"100\";\n"
        "	\"signing-status\" = \"0\";\n"
        "}"
        ,
        decode(
            "ewoJInNpZ25hdHVyZSIgPSAiQWw2enZGWkpMeVJtMjZtVlNNZGNqOVpqT0xhVFNmYVUwbXZoU2dJVEYxQUt5UzN0QXpFazhhYlky"
            "SHU3Z2NWN3FuZHpaM2JTQjQrQXcvZ1JrV2xxYWtpSVBIRy9jNjRSNEkwK3poT1pBbUhpQnFiR2FDOW1aNHNDVGJIS01xaWtUcjh5"
            "ak1qMWpKMXV0QWZpZWJvMmtnZlgzVFVlVmg5OVBXeE9YUWhpV0cwVUFBQURWekNDQTFNd2dnSTdvQU1DQVFJQ0NHVVVrVTNaV0FT"
            "MU1BMEdDU3FHU0liM0RRRUJCUVVBTUg4eEN6QUpCZ05WQkFZVEFsVlRNUk13RVFZRFZRUUtEQXBCY0hCc1pTQkpibU11TVNZd0pB"
            "WURWUVFMREIxQmNIQnNaU0JEWlhKMGFXWnBZMkYwYVc5dUlFRjFkR2h2Y21sMGVURXpNREVHQTFVRUF3d3FRWEJ3YkdVZ2FWUjFi"
            "bVZ6SUZOMGIzSmxJRU5sY25ScFptbGpZWFJwYjI0Z1FYVjBhRzl5YVhSNU1CNFhEVEE1TURZeE5USXlNRFUxTmxvWERURTBNRFl4"
            "TkRJeU1EVTFObG93WkRFak1DRUdBMVVFQXd3YVVIVnlZMmhoYzJWU1pXTmxhWEIwUTJWeWRHbG1hV05oZEdVeEd6QVpCZ05WQkFz"
            "TUVrRndjR3hsSUdsVWRXNWxjeUJUZEc5eVpURVRNQkVHQTFVRUNnd0tRWEJ3YkdVZ1NXNWpMakVMTUFrR0ExVUVCaE1DVlZNd2da"
            "OHdEUVlKS29aSWh2Y05BUUVCQlFBRGdZMEFNSUdKQW9HQkFNclJqRjJjdDRJclNkaVRDaGFJMGc4cHd2L2NtSHM4cC9Sd1YvcnQv"
            "OTFYS1ZoTmw0WElCaW1LalFRTmZnSHNEczZ5anUrK0RyS0pFN3VLc3BoTWRkS1lmRkU1ckdYc0FkQkVqQndSSXhleFRldngzSExF"
            "RkdBdDFtb0t4NTA5ZGh4dGlJZERnSnYyWWFWczQ5QjB1SnZOZHk2U01xTk5MSHNETHpEUzlvWkhBZ01CQUFHamNqQndNQXdHQTFV"
            "ZEV3RUIvd1FDTUFBd0h3WURWUjBqQkJnd0ZvQVVOaDNvNHAyQzBnRVl0VEpyRHRkREM1RllRem93RGdZRFZSMFBBUUgvQkFRREFn"
            "ZUFNQjBHQTFVZERnUVdCQlNwZzRQeUdVakZQaEpYQ0JUTXphTittVjhrOVRBUUJnb3Foa2lHOTJOa0JnVUJCQUlGQURBTkJna3Fo"
            "a2lHOXcwQkFRVUZBQU9DQVFFQUVhU2JQanRtTjRDL0lCM1FFcEszMlJ4YWNDRFhkVlhBZVZSZVM1RmFaeGMrdDg4cFFQOTNCaUF4"
            "dmRXLzNlVFNNR1k1RmJlQVlMM2V0cVA1Z204d3JGb2pYMGlreVZSU3RRKy9BUTBLRWp0cUIwN2tMczlRVWU4Y3pSOFVHZmRNMUV1"
            "bVYvVWd2RGQ0TndOWXhMUU1nNFdUUWZna1FRVnk4R1had1ZIZ2JFL1VDNlk3MDUzcEdYQms1MU5QTTN3b3hoZDNnU1JMdlhqK2xv"
            "SHNTdGNURXFlOXBCRHBtRzUrc2s0dHcrR0szR01lRU41LytlMVFUOW5wL0tsMW5qK2FCdzdDMHhzeTBiRm5hQWQxY1NTNnhkb3J5"
            "L0NVdk02Z3RLc21uT09kcVRlc2JwMGJzOHNuNldxczBDOWRnY3hSSHVPTVoydG04bnBMVW03YXJnT1N6UT09IjsKCSJwdXJjaGFz"
            "ZS1pbmZvIiA9ICJld29KSW05eWFXZHBibUZzTFhCMWNtTm9ZWE5sTFdSaGRHVXRjSE4wSWlBOUlDSXlNREUwTFRBeExURTFJREl3"
            "T2pJMk9qQTJJRUZ0WlhKcFkyRXZURzl6WDBGdVoyVnNaWE1pT3dvSkluVnVhWEYxWlMxcFpHVnVkR2xtYVdWeUlpQTlJQ0kyTkdG"
            "aE1EVTJNMkV4WkRZM056WmxabUprT1RVd1lUSTNaR1F3T0RJMU5EUXlZalZtWlRObElqc0tDU0p2Y21sbmFXNWhiQzEwY21GdWMy"
            "RmpkR2x2YmkxcFpDSWdQU0FpTVRBd01EQXdNREE1T0RZeU1URTNNU0k3Q2draVluWnljeUlnUFNBaU1pNHlJanNLQ1NKMGNtRnVj"
            "MkZqZEdsdmJpMXBaQ0lnUFNBaU1UQXdNREF3TURBNU9EWXlNVEUzTVNJN0Nna2ljWFZoYm5ScGRIa2lJRDBnSWpFaU93b0pJbTl5"
            "YVdkcGJtRnNMWEIxY21Ob1lYTmxMV1JoZEdVdGJYTWlJRDBnSWpFek9EazRORFl6TmpZeE9EVWlPd29KSW5WdWFYRjFaUzEyWlc1"
            "a2IzSXRhV1JsYm5ScFptbGxjaUlnUFNBaVJqVkdOME5GUlRBdE1qVTVNQzAwTlVJeExVRTBSalF0UlRFek0wSTNNVFpGTXpNMElq"
            "c0tDU0p3Y205a2RXTjBMV2xrSWlBOUlDSmpiMjB1ZERRdWRHaGxPVzl3TG1ScFlXMXZibVF1TmpZd0lqc0tDU0pwZEdWdExXbGtJ"
            "aUE5SUNJM016QXpNVEUwTmpZaU93b0pJbUpwWkNJZ1BTQWlZMjl0TG5RMExuUm9aVGx2Y0NJN0Nna2ljSFZ5WTJoaGMyVXRaR0Yw"
            "WlMxdGN5SWdQU0FpTVRNNE9UZzBOak0yTmpFNE5TSTdDZ2tpY0hWeVkyaGhjMlV0WkdGMFpTSWdQU0FpTWpBeE5DMHdNUzB4TmlB"
            "d05Eb3lOam93TmlCRmRHTXZSMDFVSWpzS0NTSndkWEpqYUdGelpTMWtZWFJsTFhCemRDSWdQU0FpTWpBeE5DMHdNUzB4TlNBeU1E"
            "b3lOam93TmlCQmJXVnlhV05oTDB4dmMxOUJibWRsYkdWeklqc0tDU0p2Y21sbmFXNWhiQzF3ZFhKamFHRnpaUzFrWVhSbElpQTlJ"
            "Q0l5TURFMExUQXhMVEUySURBME9qSTJPakEySUVWMFl5OUhUVlFpT3dwOSI7CgkiZW52aXJvbm1lbnQiID0gIlNhbmRib3giOwoJ"
            "InBvZCIgPSAiMTAwIjsKCSJzaWduaW5nLXN0YXR1cyIgPSAiMCI7Cn1="
            ));
}
