#ifndef CPE_DR_DEFINE_H
#define CPE_DR_DEFINE_H

#define CPE_DR_MAGIC		0x02D6

#define CPE_DR_MAX_LEVEL    32

#define	CPE_DR_MAX_VERSION		0x7fffffff

#define CPE_DR_NAME_LEN		128
#define CPE_DR_DESC_LEN		1024
#define CPE_DR_MACRO_LEN	128
#define CPE_DR_CHNAME_LEN	512
#define CPE_DR_DEFAULT_VALUE_LEN	1024

#define CPE_DR_XML_TAGSET_VERSION_0             0
#define CPE_DR_SUPPORTING_MIN_XMLTAGSET_VERSION	CPE_DR_XML_TAGSET_VERSION_0
#define CPE_DR_XML_TAGSET_VERSION_1             1
#define CPE_DR_SUPPORTING_MAX_XMLTAGSET_VERSION	CPE_DR_XML_TAGSET_VERSION_1

#endif
