#ifndef CPE_DR_ERROR_H
#define CPE_DR_ERROR_H
#include "cpe/utils/error_macros.h"
#include "cpe/dr/dr_define.h"
#include "cpe/dr/dr_external.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#define CPE_MODID_DR	0x01

typedef enum {
    CPE_DR_ERROR_NONE = 0,
	CPE_DR_ERROR_INVALID_CUTOFF_VERSION,

	CPE_DR_ERR_NET_NO_NETBUFF_SPACE,
	CPE_DR_ERROR_INVALID_REFER_VALUE,
	CPE_DR_ERROR_TOO_COMPLIEX_META,
	CPE_DR_ERROR_NET_UNSUPPORTED_TYPE,
	CPE_DR_ERROR_NET_INVALID_STRING_LEN,
	CPE_DR_ERROR_NO_HOSTBUFF_SPACE,
	CPE_DR_ERROR_NET_INVALID_VERSIONINDICATOR,
    CPE_DR_ERROR_NO_MEMORY,
    CPE_DR_ERROR_XML_PARSE,
    CPE_DR_ERROR_NO_XML_ROOT,
    CPE_DR_ERROR_INVAILD_XML_ROOT,
    CPE_DR_ERROR_NAMESPACE_CONFLICT,
    CPE_DR_ERROR_MACRO_NO_NAME_ATTR,
    CPE_DR_ERROR_INCLUDE_NO_FILE,
    CPE_DR_ERROR_NO_VERSION,
    CPE_DR_ERROR_ROOT_ID_CONFLICT,
    CPE_DR_ERROR_INVALID_TAGSET_VERSION,
    CPE_DR_ERROR_INVALID_METALIB_PARAM,
    CPE_DR_ERROR_INVALID_METALIB_CHECKSUM,
    CPE_DR_ERROR_TOO_MUCH_MACROS,
    CPE_DR_ERROR_MACRO_NO_VALUE,
    CPE_DR_ERROR_UNSUPPORTED_TYPE,
    CPE_DR_ERROR_METALIB_ROOT_NO_NAME,
    CPE_DR_ERROR_NO_SPACE_FOR_MATA,
    CPE_DR_ERROR_NO_SPACE_FOR_STRBUF,
    CPE_DR_ERROR_META_NO_NAME,
    CPE_DR_ERROR_META_NAME_CONFLICT,
    CPE_DR_ERROR_UNDEFINED_MACRO_NAME,
    CPE_DR_ERROR_META_ID_CONFLICT,
    CPE_DR_ERROR_ENTRY_NO_TYPE,
    CPE_DR_ERROR_ENTRY_INVALID_TYPE_VALUE,
    CPE_DR_ERROR_ENTRY_INVALID_IO_VALUE,
    CPE_DR_ERROR_ENTRY_INVALID_UNIQUE_VALUE,
    CPE_DR_ERROR_ENTRY_INVALID_NOTNULL_VALUE,
    CPE_DR_ERROR_ENTRY_INVALID_SIZE_VALUE,
    CPE_DR_ERROR_ENTRY_IVALID_SORTKEY_VALUE,
    CPE_DR_ERROR_ENTRY_INVALID_SELECT_VALUE,
    CPE_DR_ERROR_ENTRY_INVALID_MAXID_VALUE,
    CPE_DR_ERROR_ENTRY_INVALID_MINID_VALUE,
    CPE_DR_ERROR_ENTRY_INVALID_MAXMINID_VALUE,
    CPE_DR_ERROR_ENTRY_INVALID_COUNT_VALUE,
	CPE_DR_ERROR_ENTRY_INVALID_ID_VALUE,
	CPE_DR_ERROR_ENTRY_INVALID_DEFAULT_VALUE,
	CPE_DR_ERROR_ENTRY_INVALID_SORTMETHOD_VALUE,
	CPE_DR_ERROR_ENTRY_INVALID_DATETIME_VALUE,
	CPE_DR_ERROR_ENTRY_INVAILD_DATE_VALUE,
	CPE_DR_ERROR_ENTRY_INVALID_TIME_VALUE,
	CPE_DR_ERROR_ENTRY_INVALID_IP_VALUE,
	CPE_DR_ERROR_ENTRY_INVALID_EXTENDTOTABLE_VALUE,
    CPE_DR_ERROR_META_INVALID_SIZE_VALUE,
    CPE_DR_ERROR_META_INVALID_ALIGN_VALUE,
    CPE_DR_ERROR_META_INVALID_VERSIONINDICATOR_VALUE,
    CPE_DR_ERROR_META_INVALID_SIZETYPE_VALUE,
	CPE_DR_ERROR_META_INVALID_SPLITTABLEFACTOR,
	CPE_DR_ERROR_META_INVALID_PRIMARYKEY,
    CPE_DR_ERROR_META_INVALID_INDEXCOLUMN,
	CPE_DR_ERROR_META_INVALID_SPLITTABLEKEY,
	CPE_DR_ERROR_META_INVALID_SPLITTABLERULE,
	CPE_DR_ERROR_META_INVALID_STRICTINPUT,
	CPE_DR_ERROR_META_INVALID_DEPENDONSTRUCT,
    CPE_DR_ERROR_INVALID_PATH_VALUE,
    CPE_DR_ERROR_INVALID_OFFSET,
    CPE_DR_ERROR_NO_SPACE_TO_WRITE,
    CPE_DR_ERROR_META_NO_ENTRY,
    CPE_DR_ERROR_ENTRY_INVALID_REFER_VALUE,
    CPE_DR_ERROR_ENTRY_INVALID_SIZEINFO_VALUE,
	CPE_DR_ERROR_UNSPORTED_IOSTREAM,
	CPE_DR_ERROR_FAILED_TO_WRITE_FILE,
	CPE_DR_ERROR_FAILED_OPEN_FILE_TO_WRITE,
	CPE_DR_ERROR_INVALID_METALIB_FILE,
	CPE_DR_ERROR_FAILED_OPEN_FILE_TO_READ,
    CPE_DR_ERROR_VARIABLE_ARRAY_NO_REFER,
    CPE_DR_ERROR_VARIABLE_BEFOR_SIZEINFO,
	CPE_DR_ERROR_FAILED_CONVERT_CHINESE_TO_UNICODE,
	CPE_DR_ERROR_BREACH_KEY_RESTRICTION,
	CPE_DR_ERROR_DB_UNSUPPORTED_DBMS,
	CPE_DR_ERROR_DB_UNSUPPORTED_COMPOSITE_ARRAY,
	CPE_DR_ERROR_DB_FAILD_TO_CONNECT_SERVER,
	CPE_DR_ERROR_DB_UNSUPPORTED_OPER,
	CPE_DR_ERROR_DB_NO_PRIMARYKEY,
	CPE_DR_ERROR_DB_FAILED_TO_QUERY,
	CPE_DR_ERROR_DB_FAILED_TO_CONNECT,
	CPE_DR_ERROR_DB_FAILED_TO_GET_QUERY_RESULT,
	CPE_DR_ERROR_DB_NO_RESULT_SET,
	CPE_DR_ERROR_DB_NO_RECORD_IN_RESULTSET,
	CPE_DR_ERROR_DB_NO_EXPECTED_FIELD,
	CPE_DR_ERROR_DB_UNSUPPORTED_VARIABLE_META,
	CPE_DR_ERROR_BUILD_VERSION_CONFLICT,
	CPE_DR_ERROR_DIFF_METALIB_HASH,
	CPE_DR_ERROR_CONFICT_INDEX_NUM,
	CPE_DR_ERROR_INVALID_VERSION,
	CPE_DR_ERROR_DB_NOSPLITTABLE_KEY,
	CPE_DR_ERROR_MACROGSROUP_ATTRIBUTE,
	CPE_DR_ERROR_ENTRY_INVALID_BINDMACROSGROUP,
	CPE_DR_ERROR_VALUE_BEYOND_TYPE_FIELD,
	CPE_DR_ERROR_META_EXTENABLE_ARRAY,
	CPE_DR_ERROR_FAILED_TO_CALL_ENTER_META,
	CPE_DR_ERROR_FAILED_TO_CALL_VIST_ENTRY,
	CPE_DR_ERROR_INVALID_AUTOINCREMENT,
	CPE_DR_ERROR_INVALID_CUSTOMATTR,
	CPE_DR_ERROR_INVALID_UNIQUEENTRYNAMEVALUE,
	CPE_DR_ERROR_NAME_CONFLICT_WHEN_EXTEND,
	CPE_DR_ERROR_INVALID_PARAM,
	CPE_DR_ERROR_NEED_ADD_PREFIX_META_UNSPPORT_ENTRY_INDEX,
	CPE_DR_ERROR_SET_DB_OPTIONS,
	CPE_DR_ERROR_INVALID_VARIABLE_ARRAY_ENTRY,
	CPE_DR_ERROR_INVALID_VARIABLE_STRING_ENTRY,
    CPE_DR_ERROR_NAME_LEN_BEYOND_UPLIMIT,
    CPE_DR_ERROR_PLATFORM_CONFLICT,
    CPE_DR_ERROR_UNSOLVED_INCLUDE,
    CPE_DR_ERROR_INVALID_INDICATOR_VALUE,
    CPE_DR_ERROR_COUNT
} CPEDRERRORNO;


typedef enum
{
    CPE_DR_SUCWARN_NONE = 0,
    CPE_DR_SUCWARN_MACRO_NAME_CONFLICT,
    CPE_DR_SUCWARN_CNAME_BE_TRANCATED,
    CPE_DR_SUCWARN_DESC_VALUE_BE_TRANCATED,
    CPE_DR_SUCWARN_NO_ID,
    CPE_DR_SUCWARN_NO_NAME,
    CPE_DR_SUCWARN_NO_VERSION,
	CPE_DR_SUCWARN_TRUNCATE_DATE,
} CPEDRSUCWARNINGNO;


CPE_DR_API  char const* dr_error_string(int iErrorCode);

#undef _CPE_CUR_MODID

#ifdef __cplusplus
}
#endif

#endif
